"""create_images_and_detected_objects_tables

Revision ID: 9ef17f48ac66
Revises:
Create Date: 2024-03-18 20:21:09.947070+00:00

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ef17f48ac66'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER DATABASE photodetect SET timezone TO 'Asia/Yekaterinburg';"
    )
    
    op.create_table(
        'images',
        sa.Column(
            'id',
            sa.Integer(),
            nullable=False,
            comment='Уникальный идентификатор изображения'),
        sa.Column(
            'dt',
            sa.DateTime(),
            nullable=False,
            comment='Дата загрузки изображения'),
        sa.Column(
            'image_data',
            sa.LargeBinary(),
            nullable=False,
            comment='Байтовое представление изображения'),
        sa.PrimaryKeyConstraint('id'),
        comment='Таблица, содержащая информацию об изображениях')

    op.create_table(
        'detected_objects',
        sa.Column(
            'id',
            sa.Integer(),
            nullable=False,
            comment='Уникальный идентификатор обнаруженного объекта'),
        sa.Column(
            'image_id',
            sa.Integer(),
            nullable=False,
            comment='Идентификатор изображения'),
        sa.Column(
            'label',
            sa.String(),
            nullable=False,
            comment='Метка объекта на изображении'),
        sa.Column(
            'bounding_box',
            postgresql.JSONB(
                astext_type=sa.Text()),
            nullable=False,
            comment='Информация о прямоугольнике объекта на изображении'),
        sa.ForeignKeyConstraint(
            ['image_id'],
            ['images.id'],
            onupdate='CASCADE',
            ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        comment=(
            'Таблица, '
            'содержащая информацию об обнаруженных объектах на изображении'
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detected_objects')
    op.drop_table('images')
    # ### end Alembic commands ###
